Concurrent license model with 20 parallel API lanes support
CloudSlang/score pull request #349
Opened 2021-01-06 16:08 UTC by hdenys

Concurrent license model with 20 parallel API lanes support

2021-01-26 08:24 UTC, lucian-cm requested changes

2021-01-26 08:24 UTC, lucian-cm commented on worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
> +            if (StringUtils.isNotBlank(branchIdToCheckoutLicense) && StringUtils.equals(branchIdToCheckoutLicense, execution.getSystemContext().getBranchId())) {
I believe you might want to put isNotEmpty instead of isNotBlank

2021-01-26 08:24 UTC, lucian-cm commented on worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
> +        if ("NON_BLOCKING".equals(systemContext.get("STEP_TYPE"))) {
seems to introduce some slowness, two if and one nested if.
I would prefer to use a single if
```
Integer parallelismLevel = ...
if (parallel && correctLane) {
     systemContext.put(BRANCH_ID_TO_CHECK_OUT_LICENSE, branchId);
}
```

2021-01-26 08:24 UTC, lucian-cm commented on worker/worker-execution/score-worker-execution-impl/src/main/java/io/cloudslang/worker/execution/services/ExecutionServiceImpl.java
> +                Long executionStartTimeMillis = Optional.ofNullable((Long)execution.getSystemContext().get(SC_TIMEOUT_START_TIME)).orElse(0L);
please see formatting issue near cast

2021-01-26 08:24 UTC, lucian-cm commented on engine/orchestrator/score-orchestrator-api/src/main/java/io/cloudslang/orchestrator/services/AplsLicensingService.java
> +    String BRANCH_ID_TO_CHECK_OUT_LICENSE = "BRANCH_ID_TO_CHECK_OUT_LICENSE";
this is stored in engine context, please use a shorter name in the string BRANCH_ID_CHECKOUT, BRANCH_ID_CHECKIN

2021-01-26 09:23 UTC, lucian-cm commented on package/score-all/src/main/java/io/cloudslang/schema/EngineBeanDefinitionParser.java
> +	private void registerAplsLicensingService(Element element, ParserContext parserContext){
needs to be in the WorkerDefinitionParser

2021-02-18 07:15 UTC, lucian-cm approved these changes

2021-03-02 09:17 UTC, merged

2021-03-02 09:20 UTC, hdenys commented
Added new interface for API steps concurrent license increment/decrement.
Signed-off-by: Denys Hryvastov denys.hryvastov@microfocus.com